{
 "title": "Simnet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "node0,node1,node2,node3" }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Slot/Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_scheduler_current_slot{job=\"$node\"}",
     "legendFormat": "Slot"
    },
    {
     "expr": "core_scheduler_current_epoch{job=\"$node\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum(app_git_commit{job=\"$node\"}) by (hash)\n)\n   + on(job) group_left(version)\n(\n   0 * sum(app_version{job=\"$node\"}) by (version)\n)"
    }
   ]
  },
  {
   "title": "Errors by topic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "increase(app_log_error_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Warnings by topic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(app_log_warn_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Scheduled duties (started) by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(core_scheduler_duty_total{job=\"$node\"}[30s])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(core_scheduler_current_epoch{job=\"$node\"}[30s]) * 0.2",
     "legendFormat": "epoch boundary"
    }
   ]
  },
  {
   "title": "Validator API requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(core_validatorapi_request_latency_seconds_count{job=\"$node\"}[30s])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator API request latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(core_validatorapi_request_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Broadcast duties (completed) by type ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(core_bcast_broadcast_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(core_scheduler_current_epoch{job=\"$node\"}[30s]) * 0.2",
     "legendFormat": "epoch boundry"
    }
   ]
  },
  {
   "title": "Beacon API requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(app_eth2_latency_seconds_count{job=\"$node\"}[30s]) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Beacon API request latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}