apiVersion: v1
kind: ConfigMap
metadata:
  name: $NODE_NAME-config
  namespace: $CLUSTER_NAME
data:  
  CHARON_VALIDATOR_API_ADDRESS: "0.0.0.0:3600"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:3610"
  CHARON_MONITORING_ADDRESS: "0.0.0.0:3620"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:3630"
  CHARON_P2P_BOOTNODE_RELAY: "true"
  CHARON_P2P_BOOTNODE: $CHARON_P2P_BOOTNODE
  CHARON_BEACON_NODE_ENDPOINTS: $BEACON_NODE_ENDPOINTS
  CHARON_DATA_DIR: "/charon/$NODE_NAME"
  CHARON_LOCK_FILE: "/charon/cluster-lock.json"
  CHARON_P2P_EXTERNAL_HOSTNAME: ""
  CHARON_LOG_LEVEL: "debug"
  CHARON_NO_VERIFY: "true"
  CHARON_P2P_DISABLE_REUSEPORT: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $NODE_NAME
  name: $NODE_NAME
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NODE_NAME
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: $NODE_NAME
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: $NODE_NAME
          image: ghcr.io/obolnetwork/charon:$CHARON_VERSION
          imagePullPolicy: Always
          command: ["/usr/local/bin/charon"]
          args: ["run"]
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 10
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: $NODE_NAME-config
          volumeMounts:
            - name: validators
              mountPath: /charon/$NODE_NAME/validator_keys
            - name: private-key
              mountPath: /charon/$NODE_NAME
            - name: cluster-lock
              mountPath: /charon
      volumes:
        - name: validators
          projected:
            sources:
            - secret:
                name: $NODE_NAME-validators
        - name: private-key
          projected:
            sources:
            - secret:
                name: $NODE_NAME-charon-enr-private-key
        - name: cluster-lock
          projected:
            sources:
            - secret:
                name: $NODE_NAME-cluster-lock
---
apiVersion: v1
kind: Service
metadata:
  name: $NODE_NAME
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: $NODE_NAME
  ports:
    - name: http-bootnode
      protocol: TCP
      port: 3640
      targetPort: 3640
    - name: monitoring
      protocol: TCP
      port: 3620
      targetPort: 3620
    - name: validator-api
      protocol: TCP
      port: 3600
      targetPort: 3600
    - name: p2p-tcp
      protocol: TCP
      port: 3610
      targetPort: 3610
    - name: p2p-udp
      protocol: UDP
      port: 3630
      targetPort: 3630
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $NODE_NAME
  namespace: $CLUSTER_NAME
spec:
  selector:
    matchLabels:
      app: $NODE_NAME
  endpoints:
  - port: monitoring
