---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $VC_INDEX-lighthouse
  name: $VC_INDEX-lighthouse
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $VC_INDEX-lighthouse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: $VC_INDEX-lighthouse
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      imagePullSecrets:
        - name: docker-registry
      initContainers:
        - name: download-config
          image: amazon/aws-cli:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name:  aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          command:
            - sh
            - -ac
            - >
              aws s3 cp --recursive s3://charon-clusters-config/${CLUSTER_NAME}/node${NODE_INDEX}/validator_keys /data/lighthouse/validator_keys;
              aws s3 cp s3://charon-clusters-config/${CLUSTER_NAME}/lighthouse-validators-definitions/vc-node-${NODE_INDEX}.yaml /data/lighthouse/validator_definitions.yml;
              chown -R 1000:1000 /data/lighthouse;
          volumeMounts:
            - name: data
              mountPath: /data/lighthouse
      containers:
        - name: $VC_INDEX-lighthouse
          image: sigp/lighthouse:$LIGHTHOUSE_VERSION
          imagePullPolicy: Always
          command:
            - sh
            - -ace
            - |
              lighthouse vc \
              --http \
              --http-port=5052 \
              --http-address=0.0.0.0 \
              --http-allow-origin="*" \
              --unencrypted-http-transport \
              --beacon-nodes="http://$NODE_NAME:3600" \
              --validators-dir=/data/lighthouse \
              --network=$NETWORK \
              --init-slashing-protection \
              --metrics \
              --metrics-address "0.0.0.0" \
              --metrics-allow-origin "*" \
              --metrics-port "5064" \
              --use-long-timeouts \
              --graffiti "Obol DVT" \
              $LIGHTHOUSE_VC_EXTRA_ARGS;
          volumeMounts:
            - name: data
              mountPath: /data/lighthouse
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: $VC_INDEX-lighthouse
  namespace: $CLUSTER_NAME
  labels:
    app: $VC_INDEX-lighthouse
spec:
  selector:
    app: $VC_INDEX-lighthouse
  ports:
    - name: metrics
      protocol: TCP
      port: 8008
      targetPort: 8008
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $VC_INDEX-lighthouse
  namespace: $CLUSTER_NAME
spec:
  selector:
    matchLabels:
      app: $VC_INDEX-lighthouse
  endpoints:
  - port: metrics
