apiVersion: v1
kind: ConfigMap
metadata:
  name: import-script-config
  namespace: $CLUSTER_NAME
data:
  import-script.sh: |
    #!/bin/sh
    for f in /validator_keys/keystore-*.json; do
      cat "${f%.*}.txt" |
      /data/nimbus/nimbus_beacon_node deposits import \
      --data-dir=/data/nimbus/${NODE_NAME} \
      /validator_keys
    done
    exec /home/user/nimbus_validator_client \
      --data-dir=/data/nimbus/"${NODE_NAME}" \
      --beacon-node="http://$NODE_NAME:3600" \
      --doppelganger-detection=false \
      --metrics \
      --metrics-address=0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $VC_INDEX-nimbus
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $VC_INDEX-nimbus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: $VC_INDEX-nimbus
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: init-nimbus
          image: statusim/nimbus-eth2:$NIMBUS_VERSION
          command: [ "sh", "-c", "cp -R /home/user/nimbus_beacon_node /data/nimbus" ]
          volumeMounts:
            - name: data
              mountPath: /data/nimbus
            - name: validators
              mountPath: /validator_keys
          securityContext:
            runAsUser: 0
      containers:
        - name: $VC_INDEX-nimbus
          image: statusim/nimbus-validator-client:$NIMBUS_VERSION
          command:
            - sh
            - -ac
            - >
              cp /config/import-script.sh /data/nimbus/import-script.sh;
              chmod +x /data/nimbus/import-script.sh;
              /data/nimbus/import-script.sh;
          volumeMounts:
            - name: config
              mountPath: /config
            - name: validators
              mountPath: /validator_keys
            - name: data
              mountPath: /data/nimbus
      volumes:
        - name: config
          configMap:
            name: import-script-config
        - name: validators
          projected:
            sources:
              - secret:
                  name: $NODE_NAME-validators
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
  labels:
    app: $VC_INDEX-nimbus
spec:
  selector:
    app: $VC_INDEX-nimbus
  ports:
    - name: metrics
      protocol: TCP
      port: 8008
      targetPort: 8008
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
spec:
  selector:
    matchLabels:
      app: $VC_INDEX-nimbus
  endpoints:
    - port: metrics
