apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $VC_INDEX-nimbus
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $VC_INDEX-nimbus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: $VC_INDEX-nimbus
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: init-nimbus
          image: statusim/nimbus-eth2:$NIMBUS_VERSION
          command:
            - sh
            - -eu
            - |
              tmpkeys="/data/nimbus/nimbus-keystores";
              mkdir -p ${tmpkeys};
              for f in /validator_keys/keystore-*.json; do
                echo "Importing key ${f}";
                password=$(<"${f//json/txt}");
                cp "${f}" "${tmpkeys}";
                echo "$password" | /home/user/nimbus_beacon_node deposits import --data-dir=/home/user/data/${NODE} /home/validator_keys/tmpkeys;
                filename="$(basename ${f})";
                rm "${tmpkeys}/${filename}";
              done;
              rm -r ${tmpkeys};
          volumeMounts:
            - name: data
              mountPath: /data/nimbus
            - name: validators
              mountPath: /validator_keys
          securityContext:
            runAsUser: 0
      containers:
        - name: $VC_INDEX-nimbus
          image: statusim/nimbus-validator-client:$NIMBUS_VERSION
          command:
            - sh
            - -ac
            - "./nimbus_validator_client \\\n --log-level=debug \\\n--data-dir=/data/nimbus \\\n--metrics \\\n--metrics-address=\"0.0.0.0\" \\\n--beacon-node=\"http://$NODE_NAME:3600\" \\\n--doppelganger-detection=false \n"
          volumeMounts:
            - name: validators
              mountPath: /validator_keys
            - name: data
              mountPath: /data/nimbus
      volumes:
        - name: validators
          projected:
            sources:
              - secret:
                  name: $NODE_NAME-validators
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
  labels:
    app: $VC_INDEX-nimbus
spec:
  selector:
    app: $VC_INDEX-nimbus
  ports:
    - name: metrics
      protocol: TCP
      port: 8008
      targetPort: "8008-tcp"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $VC_INDEX-nimbus
  namespace: $CLUSTER_NAME
spec:
  selector:
    matchLabels:
      app: $VC_INDEX-nimbus
  endpoints:
    - port: metrics
