name: Deploy charon

on: 
    workflow_dispatch:
    repository_dispatch:
        types: [charon-package-published]
    push:
        branches:
            - main
        paths:
            - templates/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_CREDS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Deploy charon-prater-0
      run: |-
        cat <<EOT >> .env
        CLUSTER_NAME=charon-prater-0
        CLUSTER_SIZE=4
        CHARON_VERSION=${{ steps.charon_image_tag.outputs.tag || 'latest' }}
        TEKU_VERSION=${{ secrets.TEKU_VERSION }}
        CHARON_BOOT_NODE_ENDPOINT=${{ secrets.CHARON_BOOT_NODE_ENDPOINT }}
        BEACON_NODE_ENDPOINT=${{ secrets.PRATER_BEACON_NODE_ENDPOINT }}
        PROM_REMOTE_WRITE_END_POINT=${{ secrets.PROM_REMOTE_WRITE_END_POINT }}
        PROM_METRICS_INSTANCE_ID=${{ secrets.PROM_METRICS_INSTANCE_ID }}
        PROM_REMOTE_WRITE_TOKEN=${{ secrets.PROM_REMOTE_WRITE_TOKEN }}
        MONITORING_INGRESS_ENABLED=${{ secrets.DEPLOY_INGRESS }}
        MONITORING_DNS_BASE=${{ secrets.MONITORING_DOMAIN_NAME }}
        EOT
        ./deploy.sh
    
    - name: Deploy charon-kiln-0
      run: |-
        cat <<EOT >> .env
        CLUSTER_NAME=charon-kiln-0
        CLUSTER_SIZE=7
        CHARON_VERSION=${{ steps.charon_image_tag.outputs.tag || 'latest' }}
        TEKU_VERSION=${{ secrets.TEKU_VERSION }}
        CHARON_BOOT_NODE_ENDPOINT=${{ secrets.CHARON_BOOT_NODE_ENDPOINT }}
        BEACON_NODE_ENDPOINT=${{ secrets.KILN_BEACON_NODE_ENDPOINT }}
        PROM_REMOTE_WRITE_END_POINT=${{ secrets.PROM_REMOTE_WRITE_END_POINT }}
        PROM_METRICS_INSTANCE_ID=${{ secrets.PROM_METRICS_INSTANCE_ID }}
        PROM_REMOTE_WRITE_TOKEN=${{ secrets.PROM_REMOTE_WRITE_TOKEN }}
        MONITORING_INGRESS_ENABLED=${{ secrets.DEPLOY_INGRESS }}
        MONITORING_DNS_BASE=${{ secrets.MONITORING_DOMAIN_NAME }}
        EOT
        ./deploy.sh
