name: Delete BM Canary Clusters

on: 
    workflow_dispatch:
    workflow_call:

jobs:
  deploy:
    name: Delete Canary Clusters
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.K8S_BARE_METAL_KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Delete canary-holesky-1
      run: ./scripts/delete-cluster.sh canary-holesky-1
      shell: bash

    - name: Delete canary-holesky-2
      run: ./scripts/delete-cluster.sh canary-holesky-2
      shell: bash

    - name: Delete canary-holesky-1000
      run: ./scripts/delete-cluster.sh canary-holesky-1000
      shell: bash

    - name: Delete canary-holesky-10000
      run: ./scripts/delete-cluster.sh canary-holesky-10000
      shell: bash
