name: Delete GKE Canary Clusters

on: 
    workflow_dispatch:
    workflow_call:

jobs:
  deploy:
    name: Delete the canary clusters from GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Delete canary-holesky-1
      run: ./scripts/delete-cluster.sh canary-holesky-1
      shell: bash