name: Deploy GKE Canary Clusters

on: 
    workflow_dispatch:
      inputs:
        sha: 
          type: string
          required: true
    # repository_dispatch:
        # types: [charon-package-published]

jobs:
  delete-eks-canaries:
    uses: ObolNetwork/charon-k8s-distributed-validator-cluster/.github/workflows/delete-eks-clusters.yaml@main
    secrets: inherit

  deploy:
    name: Deploy the canary clusters
    runs-on: ubuntu-latest
    needs: delete-eks-canaries

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.inputs.sha }})
