name: Deploy charon clusters

on: 
    workflow_dispatch:
    repository_dispatch:
        types: [charon-package-published]
    push:
        branches:
            - main
        paths:
            - templates/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_CREDS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Deploy canary-goerli-1
      run: |-
        ./canary-deploy.sh charon-goerli-1
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "canary-goerli-1"

    - name: Deploy canary-goerli-2
      run: |-
        ./canary-deploy.sh charon-goerli-2

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "canary-goerli-2"

    - name: Deploy charon-gnosis-0
      run: |-
        ./deploy.sh charon-gnosis-0
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-gnosis-0"

    - name: Deploy charon-prater-0
      run: |-
        ./deploy.sh charon-prater-0
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-prater-0"

    - name: Deploy charon-prater-1
      run: |-
        ./deploy.sh charon-prater-1
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-prater-1"
