name: Deploy AWS Canary Clusters

on: 
    workflow_dispatch:
    # repository_dispatch:
    #     types: [charon-package-published]
    push:
        branches:
            - main
        paths:
            - templates/**

jobs:
  delete-gke-canaries:
    uses: ObolNetwork/charon-k8s-distributed-validator-cluster/.github/workflows/delete-gke-clusters.yaml@main
    secrets: inherit

  deploy:
    name: Deploy the canary clusters
    runs-on: ubuntu-latest
    needs: delete-gke-canaries

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE }}
        role-session-name: canary-deploy-aws
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }}--name ${{ secrets.EKS_DEV_CLUSTER }}

    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Delete canary-goerli-1
      run: ./scripts/delete-cluster.sh canary-goerli-1
      shell: bash
    - name: Deploy canary-goerli-1
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-goerli-1 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete canary-goerli-2
      run: ./scripts/delete-cluster.sh canary-goerli-2
      shell: bash
    - name: Deploy canary-goerli-2
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-goerli-2 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete charon-gnosis-0
      run: ./scripts/delete-cluster.sh charon-gnosis-0
      shell: bash
    - name: Deploy charon-gnosis-0
      run: ./scripts/deploy-cluster-with-charon-tag.sh charon-gnosis-0 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash
    
    # Disable charon-prater-0 automation until web3signer experiment is completed
    # - name: Delete charon-prater-0
    #   run: ./scripts/delete-cluster.sh charon-prater-0
    #   shell: bash
    # - name: Deploy charon-prater-0
    #   run: ./scripts/deploy-cluster-with-charon-tag.sh charon-prater-0 ${{ steps.charon_image_tag.outputs.tag }}
    #   shell: bash

    - name: Delete charon-prater-1
      run: ./scripts/delete-cluster.sh charon-prater-1
      shell: bash
    - name: Deploy charon-prater-1
      run: ./scripts/deploy-cluster-with-charon-tag.sh charon-prater-1 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash
    
    - name: Delete charon-sepolia-1780
      run: ./scripts/delete-cluster.sh charon-sepolia-1780
      shell: bash
    - name: Deploy charon-sepolia-1780
      run: ./scripts/deploy-cluster-with-charon-tag.sh charon-sepolia-1780 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete canary-holesky-1
      run: ./scripts/delete-cluster.sh canary-holesky-1
      shell: bash
    - name: Deploy canary-holesky-1
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-holesky-1 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash
