name: Deploy charon canary clusters

on: 
    workflow_dispatch:
    repository_dispatch:
        types: [charon-package-published]
    push:
        branches:
            - main
        paths:
            - templates/**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_CREDS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Deploy charon-goerli-0
      run: |-
        cat <<EOT >> .env
        NETWORK=goerli
        CLUSTER_NAME=charon-goerli-0
        CLUSTER_SIZE=4
        CHARON_VERSION=${{ steps.charon_image_tag.outputs.tag || secrets.CHARON_RELEASE_VERSION }}
        TEKU_VERSION=${{ secrets.TEKU_VERSION || 'latest' }}
        lIGTHTHOUSE_VERSION=${{ secrets.lIGTHTHOUSE_VERSION || 'latest' }}
        BEACON_NODE_ENDPOINTS=${{ secrets.GOERLI_BEACON_NODE_ENDPOINTS }}
        MONITORING_TOKEN=${{ secrets.MONITORING_TOKEN }}
        MIX_VCS=true
        VALIDATORS=1
        EOT
        ./deploy.sh

    - name: Deploy charon-goerli-1
      run: |-
        cat <<EOT >> .env
        NETWORK=goerli
        CLUSTER_NAME=charon-goerli-1
        CLUSTER_SIZE=4
        CHARON_VERSION=${{ steps.charon_image_tag.outputs.tag || secrets.CHARON_RELEASE_VERSION }}
        TEKU_VERSION=${{ secrets.TEKU_VERSION || 'latest' }}
        lIGTHTHOUSE_VERSION=${{ secrets.lIGTHTHOUSE_VERSION || 'latest' }}
        BEACON_NODE_ENDPOINTS=${{ secrets.GOERLI_BEACON_NODE_ENDPOINTS }}
        MONITORING_TOKEN=${{ secrets.MONITORING_TOKEN }}
        MIX_VCS=false
        VALIDATORS=25
        EOT
        ./deploy.sh

    - name: Deploy charon-gnosis-0
      run: |-
        cat <<EOT >> .env
        NETWORK=gnosis
        CLUSTER_NAME=charon-gnosis-0
        CLUSTER_SIZE=7
        CHARON_VERSION=${{ steps.charon_image_tag.outputs.tag || secrets.CHARON_RELEASE_VERSION }}
        TEKU_VERSION=${{ secrets.TEKU_VERSION || 'latest' }}
        lIGTHTHOUSE_VERSION=${{ secrets.lIGTHTHOUSE_VERSION || 'latest' }}
        BEACON_NODE_ENDPOINTS=${{ secrets.GNOSIS_BEACON_NODE_ENDPOINTS }}
        MONITORING_TOKEN=${{ secrets.MONITORING_TOKEN }}
        MIX_VCS=false
        VALIDATORS=1
        EOT
        ./deploy.sh

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Canary clusters are deployed successfully [Version: ${{ steps.charon_image_tag.outputs.tag || secrets.CHARON_RELEASE_VERSION }}]."
