name: Deploy Canary Clusters

on: 
    workflow_dispatch:
    repository_dispatch:
        types: [charon-package-published]
    push:
        branches:
            - main
        paths:
            - templates/**
jobs:
  deploy:
    name: Deploy the canary clusters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Delete canary-goerli-1
      run: ./delete-cluster.sh canary-goerli-1
      shell: bash
    - name: Deploy canary-goerli-1
      run: ./deploy-cluster.sh canary-goerli-1
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "canary-goerli-1"

    - name: Delete canary-goerli-2
      run: ./delete-cluster.sh canary-goerli-2
      shell: bash
    - name: Deploy canary-goerli-2
      run: ./deploy-cluster.sh canary-goerli-2
      shell: bash

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "canary-goerli-2"

    - name: Delete charon-gnosis-0
      run: ./delete-cluster.sh charon-gnosis-0
      shell: bash
    - name: Deploy charon-gnosis-0
      run: ./deploy-cluster.sh charon-gnosis-0
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-gnosis-0"

    - name: Delete charon-prater-0
      run: ./delete-cluster.sh charon-prater-0
      shell: bash
    - name: Deploy charon-prater-0
      run: ./deploy-cluster.sh charon-prater-0
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-prater-0"

    - name: Delete charon-prater-1
      run: ./delete-cluster.sh charon-prater-1
      shell: bash
    - name: Deploy charon-prater-1
      run: ./deploy-cluster.sh charon-prater-1
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-prater-1"

    - name: Delete charon-sepolia-1780
      run: ./delete-cluster.sh charon-sepolia-1780
      shell: bash
    - name: Deploy charon-sepolia-1780
      run: ./deploy-cluster.sh charon-sepolia-1780
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "charon-sepolia-1780"
