name: Deploy AWS Canary Clusters

on: 
    repository_dispatch:
        types: [charon-package-published]
    workflow_dispatch:
      inputs:
        sha: 
          type: string
          required: true
    push:
        branches:
            - main
        paths:
            - templates/** 
jobs:
  delete-gke-canaries:
    uses: ObolNetwork/charon-k8s-distributed-validator-cluster/.github/workflows/delete-gke-clusters.yaml@main
    secrets: inherit

  deploy:
    name: Deploy the canary clusters
    runs-on: ubuntu-latest
    needs: delete-gke-canaries
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name ${{ secrets.EKS_DEV_CLUSTER }}

    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Delete canary-holesky-1
      run: ./scripts/delete-cluster.sh canary-holesky-1
      shell: bash
    - name: Deploy canary-holesky-1
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-holesky-1 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash
