name: DKG Perf

on: 
  workflow_dispatch: 
jobs:
  deploy:
    name: DKG perf with AWS and GCP Relays
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run DKG Performance Test
      run: make -f Makefile makefile-loadtest-batch-runner
