name: DKG Perf

on:
  workflow_dispatch:
jobs:
  deploy:
    name: DKG perf testing
    runs-on: dkg-perf
    timeout-minutes: 360 # 6 hours
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout  

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        role-duration-seconds: 21600 # 6 hours
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Load Test Cluster Configuration
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name ${{ secrets.EKS_DEV_CLUSTER }}
        make -f makefile-loadtest-batch-runner display-test-load

    - name: Run DKG Performance Test
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name ${{ secrets.EKS_DEV_CLUSTER }}
        make -f makefile-loadtest-batch-runner
