name: DKG Run

on: 
  repository_dispatch:
      types: [charon-package-published]
  workflow_dispatch:
    inputs:
      sha: 
        type: string
        required: true
      relay: 
        type: string
        required: false
  push:
      branches:
          - main
      paths:
          - templates/** 
jobs:
  deploy:
    name: DKG run with AWS and GCP Relays
    runs-on: ubuntu-latest

    env:
      CHARON_P2P_RELAYS: ${{ github.event.inputs.relay }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run DKG Performance Test
      run: make -f Makefile makefile-loadtest-batch-runner
