name: Restart Canary Clusters

on: 
    workflow_dispatch:

jobs:
  Restart:
    name: Restart the canary clusters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
    
    - name: Restart canary-holesky-1
      run: ./restart-cluster.sh canary-holesky-1
      shell: bash
    
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "canary-holesky-1"
