name: Update BM Canary Clusters - Latest Charon

on: 
    repository_dispatch:
        types: [charon-package-published]
    workflow_dispatch:
      inputs:
        sha: 
          type: string
          required: true
    push:
        branches:
            - main
        paths:
            - templates/** 
jobs:
  deploy:
    name: Deploy Canary Clusters
    runs-on: ubuntu-latest
    # needs: delete-eks-canaries
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GHA_AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.K8S_BARE_METAL_KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Get charon image tag
      id: charon_image_tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short ${{ github.event.client_payload.sha }})

    - name: Delete canary-holesky-1
      run: ./scripts/delete-cluster.sh canary-holesky-1
      shell: bash
    - name: Deploy canary-holesky-1
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-holesky-1 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete canary-holesky-2
      run: ./scripts/delete-cluster.sh canary-holesky-2
      shell: bash
    - name: Deploy canary-holesky-2
      run: ./scripts/deploy-cluster-with-charon-tag.sh canary-holesky-2 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete canary-holesky-1000
      run: ./scripts/delete-cluster.sh canary-holesky-1000
      shell: bash
    - name: Deploy canary-holesky-1000
      run: ./scripts/deploy-cluster-with-charon-tag-perf.sh canary-holesky-1000 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash

    - name: Delete canary-holesky-10000
      run: ./scripts/delete-cluster.sh canary-holesky-10000
      shell: bash
    - name: Deploy canary-holesky-10000
      run: ./scripts/deploy-cluster-with-charon-tag-perf.sh canary-holesky-10000 ${{ steps.charon_image_tag.outputs.tag }}
      shell: bash
